### ISSUE TITLE
Why a new laravel-phpredis?

### ISSUE THREAD

**Issue by Swanty** [Barbery/laravel-phpredis#1]
Why a new laravel-phpredis?

There already exists
https://github.com/vetruvet/laravel-phpredis
and
https://github.com/tillkruss/laravel-phpredis

Maybe it would be a better idea to contribute to the existing ones?

**Comment by Barbery** [comment]
Hi Swanty,
The big difference between those libraries you notice, is my library implement Cache support by framework, you can easy to use redis driver in Cache and Session. 
Now in my company, I use this library in production with redis-cluster, Cache and Session work fine. 
Yes, You are right, Maybe contribute to the existing one is best. But I still have some feature not support, after finish it, maybe I will post a pull request to those repo.
Thank you!

**Comment by Swanty** [comment]
Oh, I thought sessions worked with others too. Interesting...
I'm conflicted between all these laravel-phpredis and don't know which one to use or support =/

**Comment by Barbery** [comment]
You can use it, and choose one you like
