### ISSUE TITLE
Missing argument 2 for Barbery\Providers\RedisServiceProvider::Barbery\Providers\{closure}()

### ISSUE THREAD

**Issue by xiangweilee** [Barbery/laravel-phpredis#4]
To get rid of this error, I set $config default to `array()`
```php
Cache::extend('redis', function ($app, $config = array()) {
// ...
});
```
See https://github.com/Barbery/laravel-phpredis/blob/master/src/Providers/RedisServiceProvider.php#L29

**Comment by Barbery** [comment]
Hi, can you tell me your laravel's version?

**Comment by xiangweilee** [comment]
Running `php artisan --version` return me `Laravel Framework version 4.2.17`

**Comment by Barbery** [comment]
please upgrade your laravel to 5.2.x at least.
Now the master branch is for the latest version of laravel(5.3.x), and the v5.2.x branch is for laravel 5.2.x
