### ISSUE TITLE
Redis Single/Cluster mixed mode

### ISSUE THREAD

**Issue by sgohl** [Barbery/laravel-phpredis#9]
Because of 
```
        'cluster' => env('REDIS_CLUSTER', false),
```
is already in the top layer of the redis config array, how could it be possible to configure multiple clusters as well as multiple single redis instances?

this is how my not-working config looks like:
![image](https://user-images.githubusercontent.com/8873017/92119055-93c3a900-edf7-11ea-8bb0-6db0c7185bc7.png)

any help is appreciated!

**Comment by Barbery** [comment]
I think it is very low probability to use mixed mode. You can use the .env file like .env.product and .env.dev to switch.

**Comment by sgohl** [comment]
I don't want to switch. that would not be mixed mode, that would just be using one or the other.
I can't believe everyone is just using a single redis store, no one having bigger project than personal blog?
